#!/usr/bin/bash
#
# Copyright (c) <YEAR> Anthony J. Greenberg
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Display speaker/headphones volume
#

pctlHead=$( pactl list sinks | grep -A 7 -e 'Name: .\+analog-stereo' )
isMute=$( echo "$pctlHead" | grep Mute | awk '{print $2}' )
vol=$( echo "$pctlHead" | grep -m 1 Volume | awk '{print $5}' | sed 's/%$//' )
outID=$( pactl list sinks | grep 'Active Port:' | grep analog | cut -d '-' -f3 )
if [[ $outID = "headphones" ]]; then
	outIcon=""
elif [[ $outID = "speaker" ]]; then
	outIcon="蓼"
else
	outIcon=""
fi

if [[ $isMute = "yes" ]]; then
	echo -en "$outIcon $vol% \ufa80"
elif [[ $vol -le 20 ]]; then
	echo -en "$outIcon $vol% \uf027"
elif [[ $vol -le 70 ]]; then
	echo -en "$outIcon $vol% \ufa7f"
else
	echo -en "$outicon $vol% \ufa7d"
fi

