#!/usr/bin/bash

#
# Copyright (c) 2020 Anthony J. Greenberg
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Queries NVIDIA for the GPU load and temperature, and displays them nicely
#

usageVal=$( nvidia-smi --query --display=UTILIZATION | grep -A 5 'GPU Utilization' | tail -1 | cut -d ':' -f2 | awk '{print $1}' )

tempValue=$( nvidia-smi --query --display=TEMPERATURE | grep 'GPU Current' | cut -d ':' -f2 | awk '{print $1}' )

if [[ $tempValue -le 35 ]]; then
	printf "\uf008 %3s %% \ue20c %2s°C" "$usageVal" "$tempValue"
elif [[ $tempValue -le 80 ]]; then
	printf "\uf008 %3s %% \ue20a %2s°C" "$usageVal" "$tempValue"
else
	printf "\uf008 %3s %% \ue20b %2s°C" "$usageVal" "$tempValue"
fi

